import React, { useState } from 'react';
import { createRoot } from 'react-dom/client';
import { flushSync } from 'react-dom';
import { INITIAL_COUNTS, LETTER_VALUES } from '@bestword/engine';
import { LETTERS, VOWELS, isVowel, type Board, type Letter } from '@bestword/contracts';
import { clickSquare, emptyDraft, inferMove, typeLetter } from '../../../apps/web/src/draft';
import type { Asset, Example, ExampleWord, FrameInput, Scene } from './types';
import './style.css';

const NAVY = '#142b3b', GOLD = '#cfab67', TEAL = '#277b76';
const clamp = (n: number, min = 0, max = 1) => Math.min(max, Math.max(min, n));
const ease = (n: number) => { const x = clamp(n); return x * x * (3 - 2 * x); };
const at = (p: number, start: number, length = .08) => ease((p - start) / length);
const coord = (index: number) => `${String.fromCharCode(65 + index % 15)}${Math.floor(index / 15) + 1}`;
const defaultScene: Scene = { id: 'welcome', chapter: 'HOW TO PLAY', title: 'Welcome to BestWord', kind: 'title', narration: '', bullets: ['Two players. One shared board.', 'Build words. Connect bridges. Make every letter count.'] };
let updateFrame: (input: FrameInput) => void;

function Label({children}: {children: React.ReactNode}) { return <div className="label">{children}</div>; }
function BulletList({items, large = false}: {items: string[]; large?: boolean}) { return <div className={`bullet-list ${large ? 'large' : ''}`}>{items.map((text, i) => <div className="bullet" key={i}><span className="bullet-mark">{String(i + 1).padStart(2, '0')}</span><p>{text}</p></div>)}</div>; }
function Tile({letter, size = 84, vowel, muted = false}: {letter: string; size?: number; vowel?: boolean; muted?: boolean}) { return <div className={`letter-tile ${vowel ? 'vowel' : ''} ${muted ? 'muted' : ''}`} style={{width: size, height: size, fontSize: size * .53}}><span>{letter}</span>{LETTERS.includes(letter as Letter) && <small style={{fontSize: Math.max(13, size * .19)}}>{LETTER_VALUES[letter as Letter]}</small>}</div>; }
function Panel({children, className = ''}: {children: React.ReactNode; className?: string}) { return <div className={`panel ${className}`}>{children}</div>; }

function Header({scene}: {scene: Scene}) { return <header><div className="brand"><span className="brand-letter">B<small>8</small></span><span>BESTWORD</span></div><div className="heading"><div className="chapter">{scene.chapter}</div><h1 className={scene.title.length > 48 ? 'long' : ''}>{scene.title}</h1></div><div className="edition">THE COMPLETE<br/>PLAYER’S GUIDE</div></header>; }
function Footer({scene, progress}: {scene: Scene; progress: number}) { return <><div className="footer"><span>{scene.chapter}</span><span>BESTWORD · HOW TO PLAY</span></div><div className="progress-track"><div style={{width: `${clamp(progress) * 100}%`}}/></div><div className="caption-reserve"/></>; }

function Title({scene, p}: {scene: Scene; p: number}) { return <div className="title-scene"><div className="title-kicker">A NEW WAY TO BUILD WORDS</div><div className="hero-word">{'BESTWORD'.split('').map((letter, i) => <div key={i} style={{opacity: at(p, i * .022, .07), transform: `translateY(${(1 - at(p, i * .022, .07)) * 20}px)`}}><Tile letter={letter} size={133}/></div>)}</div><h2>Make every letter count.</h2><div className="title-rule"/><p>{scene.bullets[0] || 'Two players. One shared board.'}</p><div className="title-chips"><span>15 × 15 board</span><span>English words</span><span>Bridges & strategy</span></div>{scene.bullets[1] && <div className="title-secondary">{scene.bullets[1]}</div>}</div>; }

function LettersScene({scene}: {scene: Scene}) { return <div className="letters-scene"><div className="stat-line"><div><strong>267</strong><span>tiles in the starting bag</span></div><div><strong>90</strong><span>vowels · A E I O U Y</span></div><div><strong>177</strong><span>consonants · private racks</span></div></div><div className="letter-table">{LETTERS.map(letter => <div className={`letter-cell ${isVowel(letter) ? 'vowel-cell' : ''}`} key={letter}><Tile letter={letter} size={78} vowel={isVowel(letter)}/><strong>{LETTER_VALUES[letter]} <small>{LETTER_VALUES[letter] === 1 ? 'point' : 'points'}</small></strong><span>× {INITIAL_COUNTS[letter]} <small>tiles</small></span></div>)}</div><div className="letter-key"><span><i className="dot teal"/>Vowels come from the shared bag. Y is a vowel.</span><span><i className="dot gold"/>Consonants come from your private rack.</span></div><p className="footnote">Values and starting quantities for all 26 letters · no blank tiles · no bonus squares</p></div>; }

function DrawScene({scene, p}: {scene: Scene; p: number}) { const cards = [{range:'0–8', count:8, draw:2, label:'Draw 2 consonants'}, {range:'9', count:9, draw:1, label:'Draw 1 consonant'}, {range:'10', count:10, draw:0, label:'Your rack is full'}]; return <div className="draw-scene"><div className="center-intro"><Label>EVERY TURN BEGINS WITH AN AUTOMATIC DRAW</Label><h2>Look at your rack before the draw.</h2></div><div className="draw-cards">{cards.map((card, index) => <Panel className={`draw-card ${p > .12 + index * .16 ? 'active-card' : ''}`} key={card.range}><Label>CONSONANTS ON YOUR RACK</Label><div className="draw-number">{card.range}<span>→</span><strong>+{card.draw}</strong></div><div className="mini-rack">{Array.from({length:10}, (_, i) => <div key={i} className={i < card.count ? 'filled' : 'added'}>{i < card.count ? '•' : '+'}</div>)}</div><h3>{card.label}</h3><p>{card.draw ? 'If enough consonants remain in the bag.' : 'No consonants are drawn this turn.'}</p></Panel>)}</div><div className="draw-note"><span className="round-icon">10</span><p>Ten consonants is the maximum. Draw fewer if the bag runs low;<br/>draw none if no consonants remain.</p></div></div>; }

interface BoardProps { board: Board; before?: Board; newIndices?: Set<number>; pillars?: Set<number>; spans?: number[]; cursor?: number | null; direction?: 'H' | 'V'; bounds?: {r0:number;r1:number;c0:number;c1:number}; highlight?: Set<number>; maxWidth?: number; maxHeight?: number }
function boundsFor(board: Board, fullColumns = false) { const occupied = board.flatMap((letter,i) => letter ? [i] : []); if (!occupied.length) return {r0:0,r1:14,c0:0,c1:14}; const rows=occupied.map(i=>Math.floor(i/15)), cols=occupied.map(i=>i%15); return {r0:Math.max(0,Math.min(...rows)-1),r1:Math.min(14,Math.max(...rows)+1),c0:fullColumns?0:Math.max(0,Math.min(...cols)-1),c1:fullColumns?14:Math.min(14,Math.max(...cols)+1)}; }
function BoardDiagram({board, before, newIndices = new Set(), pillars = new Set(), spans = [], cursor = null, direction = 'H', bounds = boundsFor(board), highlight = new Set(), maxWidth=1100, maxHeight=575}: BoardProps) {
  const rows=bounds.r1-bounds.r0+1, cols=bounds.c1-bounds.c0+1, margin=40, size=Math.min((maxWidth-margin-8)/cols,(maxHeight-margin-8)/rows,105), width=cols*size+margin+8,height=rows*size+margin+8;
  return <svg className="board-diagram" width={width} height={height} viewBox={`0 0 ${width} ${height}`} aria-label="Annotated BestWord board"><rect x={margin-2} y={margin-2} width={cols*size+4} height={rows*size+4} rx="4" fill={NAVY}/>{Array.from({length:cols},(_,i)=><text key={`c${i}`} x={margin+(i+.5)*size} y={26} textAnchor="middle" fontSize={21} fontWeight="600" fill="#647273">{String.fromCharCode(65+bounds.c0+i)}</text>)}{Array.from({length:rows},(_,i)=><text key={`r${i}`} x={24} y={margin+(i+.5)*size+7} textAnchor="middle" fontSize={21} fontWeight="600" fill="#647273">{bounds.r0+i+1}</text>)}{Array.from({length:rows},(_,r)=>Array.from({length:cols},(_,c)=>{const index=(bounds.r0+r)*15+bounds.c0+c,letter=board[index],x=margin+c*size,y=margin+r*size,isNew=newIndices.has(index)&&!!letter,isPillar=pillars.has(index),spanNumber=spans.indexOf(index)+1;return <g key={index}><rect x={x+.5} y={y+.5} width={size-1} height={size-1} fill={isNew?'#e0bd77':letter?'#fffdf5':'#e5e0d3'} stroke="#bcb7a8" strokeWidth={1}/>{highlight.has(index)&&<rect x={x+2} y={y+2} width={size-4} height={size-4} fill="none" stroke="#597d91" strokeWidth={2}/>} {isNew&&<rect x={x+3} y={y+3} width={size-6} height={size-6} rx={2} fill="none" stroke="#a4772c" strokeWidth={2}/>} {isPillar&&<rect x={x+4} y={y+4} width={size-8} height={size-8} rx={3} fill="none" stroke={TEAL} strokeWidth={4}/>} {letter&&<><text x={x+size*.46} y={y+size*.65} textAnchor="middle" fontFamily="Georgia,serif" fontSize={size*.52} fontWeight={600} fill={NAVY}>{letter}</text><text x={x+size-8} y={y+size-7} textAnchor="end" fontSize={Math.max(11,size*.17)} fill="#576267">{LETTER_VALUES[letter]}</text></>}{cursor===index&&!letter&&<text x={x+size/2} y={y+size*.72} textAnchor="middle" fontSize={size*.65} fill="#916423">{direction==='H'?'⇨':'⇩'}</text>}{spanNumber>0&&<><circle cx={x+size-12} cy={y+12} r={Math.min(12,size*.21)} fill="#795491"/><text x={x+size-12} y={y+16.5} textAnchor="middle" fontSize={13} fontWeight={700} fill="white">{spanNumber}</text></>}{isPillar&&<circle cx={x+9} cy={y+9} r="5" fill={TEAL}/>}</g>;}))}</svg>;
}
function Legend({spans = false}: {spans?: boolean}) { return <div className="board-legend"><span><i className="legend-square old"/>Already on the board</span><span><i className="legend-square new"/>New tile</span>{spans&&<><span><i className="legend-square pillar"/>Pillar</span><span><i className="legend-number">1</i>Span</span></>}</div>; }
function wordGeometry(word: ExampleWord, before: Board): ExampleWord { const indices=word.indices || Array.from({length:word.word.length},(_,i)=>(word.row+(word.direction==='V'?i:0))*15+word.column+(word.direction==='H'?i:0)); const occupied=indices.filter(i=>before[i]); const first=occupied[0],last=occupied.at(-1); const firstAt=first===undefined?-1:indices.indexOf(first),lastAt=last===undefined?-1:indices.indexOf(last); return {...word,indices,pillars:word.pillars|| (first===undefined?[]:first===last?[first]:[first,last!]),spanIndices:word.spanIndices||indices.filter((index,i)=>i>firstAt&&i<lastAt&&!before[index])}; }
function ScoreScene({example,p,scene,t}: {example?:Example|undefined;p:number;scene:Scene;t:number}) {
  if(!example)return <div className="empty-message">A scoring example is required for this scene.</div>;
  const words=example.words.map(word=>wordGeometry(word,example.beforeBoard)),principal=words.find(word=>word.isPrincipal)||words[0]!;
  const cues=scene.visualCues;
  const count=cues?(cues.placedAt<=0?example.newTiles.length:Math.ceil(at(t,cues.placedAt,.65)*example.newTiles.length)):(p<.17?0:p<.34?Math.ceil(at(p,.17,.14)*example.newTiles.length):example.newTiles.length);
  const showPillars=cues?t>=cues.pillarsAt:p>=.34,showSpans=cues?t>=cues.spansAt:p>=.34;
  const calculationVisible=(index:number)=>cues?t>=(cues.calculationsAt[index]??Infinity):p>=.51+index/words.length*.34;
  const phase=words.some((_,index)=>calculationVisible(index))?3:showPillars||showSpans?2:count?1:0;
  const activeIndex=cues?Math.max(0,...cues.focusAt.flatMap((time,index)=>t>=time&&index<words.length?[index]:[])):(phase<3?words.indexOf(principal):Math.min(words.length-1,Math.floor(clamp((p-.51)/.34)*words.length))); const active=words[activeIndex]!;
  const newIndices=new Set(example.newTiles.slice(0,count).map(tile=>tile.row*15+tile.column));
  const board=example.beforeBoard.map((letter,index)=>newIndices.has(index)?example.afterBoard[index]!:letter);
  const labels=['The existing position','Place at least two new tiles','Find the pillars. Count the spans.','Score every word formed'];
  return <div className={`score-scene ${words.length>4?'many-words':''}`}><div className="score-left"><div className="scene-step"><span>{String(phase+1).padStart(2,'0')}</span><h2>{labels[phase]}</h2></div><div className="board-stage"><BoardDiagram board={board} before={example.beforeBoard} newIndices={newIndices} pillars={new Set(showPillars?active.pillars:[])} spans={showSpans?active.spanIndices:[]} highlight={new Set(phase>=2?active.indices:[])} bounds={boundsFor(example.afterBoard,example.id==='anopias')}/></div><Legend spans/><div className="score-board-note"><strong>{phase>=2?active.word:principal.word}</strong><span>{phase>=2?active.spans?`${active.spans} ${active.spans===1?'span':'spans'} between ${active.pillars.map(coord).join(' and ')}`:active.pillars.length<2?'Fewer than two old tiles → no spans':'No empty squares between two old pillars':`${example.newTiles.length} new tiles · ${example.notation}`}</span></div></div><div className="score-right"><Label>SCORING EXAMPLE · MOVE BREAKDOWN</Label><div className="score-word-list">{words.map((word,index)=><div key={`${word.word}-${index}`} className={`score-word ${activeIndex===index&&phase>=2?'selected':''}`}><div className="word-heading"><strong>{word.word}</strong><span>{word.isPrincipal?'PRINCIPAL':word.spans?'SECONDARY · BRIDGE':'SECONDARY'}</span></div><div className="equation" style={{opacity:calculationVisible(index)?1:.18}}>{word.isPrincipal?<><span>{word.letterSum}</span><b>×</b><span>(<em>{word.consonants}</em> + <i>{word.spans}</i>)</span><b>=</b><strong>{word.score}</strong></>:<><span>{word.letterSum}</span>{word.spans>0&&<><b>×</b><span>2</span></>}<b>=</b><strong>{word.score}</strong></>}</div>{word.isPrincipal&&<div className="formula-key"><span>letter sum</span><span><em>consonants</em> + <i>spans</i></span></div>}</div>)}</div><div className="score-total" style={{opacity:(cues?t>=cues.totalAt:p>.85)?1:.3}}><span>TOTAL FOR THIS MOVE</span><strong>{example.score}<small>points</small></strong></div></div></div>;
}

function InputScene({p,scene,t}: {p:number;scene:Scene;t:number}) {
  const before=Array<Letter|null>(225).fill(null);'MAST'.split('').forEach((s,i)=>{before[107+i]=s as Letter;});'PIECE'.split('').forEach((s,i)=>{before[113+i]=s as Letter;});
  const vowels={A:16,E:24,I:16,O:13,U:13,Y:8};const rack:Letter[]=['R'];
  const clicked=clickSquare(emptyDraft(),before,111),typedE=typeLetter(clicked,before,'E',rack,vowels).draft,typedER=typeLetter(typedE,before,'R',rack,vowels).draft;
  const cues=scene.inputCues;
  const stage=cues?(t<cues.clickAt?0:t<cues.typeEAt?1:t<cues.typeRAt?2:t<cues.submitAt?3:4):(p<.18?0:p<.35?1:p<.48?2:p<.85?3:4);
  const drafts=[emptyDraft(),clicked,typedE,typedER,typedER];const draft=drafts[stage]!;
  const board=[...before];for(const tile of draft.tiles)board[tile.row*15+tile.column]=tile.letter;
  const move=inferMove(draft,before);const captions=['Two existing pieces. Two gaps to fill.','Click G8: the first click points horizontally.','Type E. It comes from the shared vowels.','Type R. The existing prefix and suffix are included.','Press Enter or choose Play word.'];
  return <div className="input-scene"><div className="scene-step"><span>{String(stage+1).padStart(2,'0')}</span><h2>{captions[stage]}</h2></div><div className="input-board"><BoardDiagram board={board} newIndices={new Set(draft.tiles.map(tile=>tile.row*15+tile.column))} cursor={draft.cursor} direction={draft.direction} bounds={{r0:6,r1:8,c0:1,c1:13}} maxWidth={1768} maxHeight={385}/></div><Legend/><div className="key-steps">{['Click G8','E','R','Enter'].map((key,i)=><div className={`key-step ${stage===i+1?'current':''} ${stage>i+1?'complete':''}`} key={i}><span className={i===0?'mouse-key':'keyboard-key'}>{key}</span><small>{['Select square','Add vowel','Add consonant','Play word'][i]}</small></div>)}</div><div className="inferred-word"><Label>THE COMPLETE PRINCIPAL WORD</Label><strong>{stage>=3?move?.word:'MAST · · PIECE'}</strong><span>Only the E and R are newly placed.</span></div><p className="footnote">Teaching board · The app includes any continuous existing prefix or suffix automatically.</p></div>;
}

function AppScene({scene,asset,p}: {scene:Scene;asset?:Asset|undefined;p:number}) { const portrait=!!asset?.width&&!!asset?.height&&asset.height>asset.width; const zoom=['directional-entry','edit-entry'].includes(scene.id)?'zoom-board':scene.id==='clocks'?'zoom-clocks':''; return <div className={`app-scene ${portrait?'portrait':''} ${zoom}`}><div className="footage-column"><div className={`device-frame ${portrait?'phone-frame':''}`}><div className="device-bar"><div><i/><i/><i/></div><span>BESTWORD · ACTUAL APPLICATION{zoom?' · DETAIL VIEW':''}</span><span className="live-dot"/></div><div className="media-well">{asset?.type==='video'?<video key={asset.url} src={asset.url} muted playsInline preload="auto"/>:asset?.type==='image'?<img src={asset.url} alt="BestWord application"/>:<div className="media-placeholder"><div className="brand-letter">B<small>8</small></div><p>BestWord application</p></div>}</div></div></div><div className="app-notes"><Label>ON YOUR SCREEN</Label><BulletList items={scene.bullets}/>{portrait&&<div className="touch-note"><span>☝</span><p>Tap the board.<br/>Tap your tiles.<br/>Play your word.</p></div>}{['directional-entry','edit-entry'].includes(scene.id)&&<div className="key-callouts"><span><b>⇨</b> Across</span><span><b>⇩</b> Down</span>{scene.id==='edit-entry'&&<span><b>⌫</b> Erase last tile</span>}<span><b>Enter</b> Play word</span></div>}<div className="app-note-line"/><span className="app-note-caption">{scene.id.toLowerCase().includes('replay')?'Review the board one move at a time.':scene.id.toLowerCase().includes('spectator')?'Public board. Private racks.':'Shown in the working BestWord app.'}</span></div></div>; }

function VowelsScene(){return <div className="vowels-scene"><div className="vowel-hero">{VOWELS.map(letter=><Tile letter={letter} size={138} vowel key={letter}/>)}</div><div className="vowel-source"><Panel><Label>SHARED VOWELS</Label><h2>Choose from the bag.</h2><p>Take A, E, I, O, U or Y when placing your word.<br/>Everyone sees the remaining vowel counts.</p><div className="source-icon bag-icon">A E I<br/>O U Y</div></Panel><Panel><Label>PRIVATE CONSONANTS</Label><h2>Choose from your rack.</h2><p>Your rack holds up to 10 consonants.<br/>Only you can see those letters.</p><div className="private-rack">{'BCDRS'.split('').map(letter=><Tile key={letter} letter={letter} size={62}/>)}<span>+ 5 spaces</span></div></Panel></div><div className="vowels-emphasis">Y belongs with the vowels.</div></div>;}

function LegalityScene({secondary=false}: {secondary?:boolean}){const base=Array<Letter|null>(225).fill(null);let left:Board,right:Board,leftNew:Set<number>,rightNew:Set<number>;if(secondary){left=[...base];left[1]='R';left[15]='C';left[16]='A';left[17]='T';right=[...left];right[31]='N';leftNew=new Set([15,16,17]);rightNew=new Set(leftNew);}else{base[16]='C';base[17]='A';base[18]='T';left=[...base];left[19]='S';right=[...base];right[19]='E';right[20]='R';leftNew=new Set([19]);rightNew=new Set([19,20]);}return <div className="legality-scene"><div className="comparison-heading"><Label>{secondary?'EXAMINE THE PERPENDICULAR WORD TOO':'TEACHING EXAMPLE · OLD CAT IS ALREADY ON THE BOARD'}</Label><h2>{secondary?'The principal can be valid while a crossing fails.':'A longer word still needs at least two new tiles.'}</h2></div><div className="legal-pair">{[{board:left,newTiles:leftNew,good:false,title:secondary?'RA has only 2 letters':'CATS adds only 1 tile',detail:secondary?'The two-letter secondary word makes this move invalid.':'Adding only S does not meet the two-new-tile minimum.'},{board:right,newTiles:rightNew,good:true,title:secondary?'RAN has 3 letters':'CATER adds 2 tiles',detail:secondary?'CAT and RAN are both valid dictionary words.':'Adding E and R makes a connected, continuous word.'}].map((item,i)=><Panel className={`legal-panel ${item.good?'good':'bad'}`} key={i}><div className="verdict"><span>{item.good?'✓':'×'}</span><h3>{item.title}</h3></div><div className="legal-board"><BoardDiagram board={item.board} newIndices={item.newTiles} bounds={secondary?{r0:0,r1:2,c0:0,c1:2}:{r0:0,r1:2,c0:0,c1:6}} highlight={secondary?new Set(item.good?[1,16,31]:[1,16]):new Set()} maxWidth={730} maxHeight={295}/></div><p>{item.detail}</p></Panel>)}</div><Legend/><p className="footnote">{secondary?'Board fragments shown. Every complete word formed must contain 3–15 letters and be in the dictionary.':'New tiles can be vowels, consonants, or any mix. All must lie in one row or one column.'}</p></div>;}

function ReadyScene({p}:{p:number}){const countdown=p<.25?'3':p<.45?'2':p<.65?'1':'PLAY';return <div className="ready-scene"><div className="ready-players"><Panel><div className="avatar-large">A</div><h2>Player one</h2><span className="ready-badge">✓ Connected</span></Panel><div className="countdown-display"><Label>SHARED COUNTDOWN</Label><strong>{countdown}</strong><span>Random first player</span></div><Panel><div className="avatar-large">B</div><h2>Player two</h2><span className="ready-badge">✓ Connected</span></Panel></div><div className="ready-rack"><Label>EMPTY STARTING RACKS</Label><div>{Array.from({length:10},(_,i)=><span key={i}/>)}</div><p>The first turn begins with the automatic consonant draw.</p></div><div className="ready-note"><strong>25 seconds</strong><span>A pre-start no-show cancels the game without a winner.</span></div></div>;}

function HistoryRuleScene(){return <div className="history-rule-scene"><div className="history-column"><Label>PRINCIPAL-WORD HISTORY</Label><Panel><span>Opening word</span><strong>MASTERPIECE</strong><span>Already used</span><strong>BOOMERANG</strong><div className="history-stamp">Both players share this history</div></Panel></div><div className="history-arrow">→</div><div className="history-examples"><Panel className="history-rejected"><span className="status-symbol">×</span><div><h2>BOOMERANG</h2><p>The same principal word cannot be played again.</p></div></Panel><Panel className="history-allowed"><span className="status-symbol">✓</span><div><h2>BOOMERANGS</h2><p>A different complete word can be legal.<br/>It still needs 2+ new tiles and every crossing must work.</p></div></Panel><p className="history-free">Secondary words may repeat.</p></div></div>;}

function RejectedScene({p}:{p:number}){return <div className="rejected-scene"><Panel className="draft-card"><Label>YOUR EDITABLE DRAFT</Label><div className="rejected-tiles">{'QZX'.split('').map((letter,i)=><Tile letter={letter} size={122} key={i}/>)}</div><div className="rejection-banner"><span>×</span>Not in the dictionary</div><div className="draft-actions"><span>⌫ Erase</span><span>Clear</span><span>Play word</span></div><p>Correct the same draft and try again.</p></Panel><div className="rejection-facts"><div className="running-clock"><Label>YOUR CLOCK KEEPS RUNNING</Label><strong>4:{String(59-Math.floor(p*12)).padStart(2,'0')}</strong></div><BulletList items={['No points are scored.','No extra consonants are drawn.','No 30-second increment is added.']}/></div></div>;}

function ScoreIntroScene(){return <div className="score-intro-scene"><Label>EVERY LETTER COUNTS — OLD AND NEW</Label><div className="score-letter-demo">{'SOS'.split('').map((letter,i)=><div className={i===1?'old-example':'new-example'} key={i}><Tile letter={letter} size={153}/><span>{i===1?'OLD TILE':'NEW TILE'}</span><strong>{LETTER_VALUES[letter as Letter]}</strong></div>)}</div><div className="letter-sum-demo">2 <span>+</span> 1 <span>+</span> 2 <span>=</span> <strong>5</strong></div><p>This is the <strong>letter sum</strong>. Apply the appropriate multiplier next.</p><div className="score-role-labels"><span>PRINCIPAL · the word in your move direction</span><span>SECONDARY · a perpendicular word formed</span></div></div>;}

function FormulasScene(){return <div className="formulas-scene"><Panel className="principal-formula"><Label>PRINCIPAL WORD</Label><div className="formula-large">Letter sum <b>×</b> (<em>consonants</em> + <i>spans</i>)</div><p>Count every letter, including the old tiles.</p></Panel><Panel className="secondary-formula"><Label>SECONDARY WORD</Label><div className="secondary-two"><div><span>BRIDGE</span><strong>Letter sum × 2</strong></div><div><span>NO BRIDGE</span><strong>Letter sum × 1</strong></div></div><p>Evaluate each secondary word separately, then add all scores.</p></Panel><div className="formula-footnotes"><span>Y is a vowel.</span><span>All-vowel principal + 0 spans = 0 points.</span><span>Bridge scoring does not override placement rules.</span></div></div>;}

function EndingScene(){return <div className="ending-scene"><div className="ending-players"><Panel><span className="passed-pill">PASSED</span><h2>Player one</h2><strong>147</strong><span>points</span></Panel><div className="ending-winner"><Label>BOTH PLAYERS HAVE PASSED</Label><strong>Higher score wins</strong><span>Equal totals mean a draw.</span></div><Panel><span className="passed-pill">PASSED</span><h2>Player two</h2><strong>186</strong><span>points</span><i>WINNER</i></Panel></div><div className="empty-bag-note"><span className="bag-outline">0</span><div><h3>An empty bag does not end the game.</h3><p>Use the tiles available to you, or pass when you are finished.</p></div></div></div>;}

function RecoveryScene({scene,p}:{scene:Scene;p:number}){const recovery=scene.id==='recovery';return <div className={`recovery-scene ${recovery?'paused-scene':''}`}><div className="recovery-top"><div className="recovery-symbol">{recovery?'Ⅱ':'↻'}</div><div><Label>{recovery?'CONFIRMED SERVICE INTERRUPTION':'PLAYER CONNECTION LOST'}</Label><h2>{recovery?'Play pauses safely.':'Reconnect promptly.'}</h2></div></div><div className="recovery-panels"><Panel><Label>{recovery?'AFTER SERVICE RECOVERY':'AFTER SERVER DETECTION'}</Label><strong className="seconds-big">{recovery?'120':'25'}<span>seconds</span></strong><p>{recovery?'Remaining players have up to two minutes to return.':'Return before the allowance expires.'}</p></Panel><Panel><Label>{recovery?'CLOCKS AND RECONNECT ALLOWANCES':'YOUR ACTIVE CLOCK'}</Label><strong className="recovery-clock">{recovery?'PAUSED':`4:${String(52-Math.floor(p*8)).padStart(2,'0')}`}</strong><p>{recovery?'They stop during a confirmed infrastructure pause.':'The active clock continues to run.'}</p></Panel></div><div className="recovery-outcome">{recovery?<><strong>Everyone returns → short countdown → play resumes</strong><span>A missing player after recovery closes the game without a winner.</span></>:<><strong>Missing the deadline loses, regardless of score.</strong><span>A player who already passed is exempt.</span></>}</div></div>;}

function RulesScene({scene,p}: {scene:Scene;p:number}) { return <div className="rules-scene"><div className="rule-hero"><div className="board-mini">{Array.from({length:225},(_,i)=><i className={Math.floor(i/15)===7||i%15===7?'crossing':''} key={i}/>)}</div><div className="board-size"><strong>15 × 15</strong><span>No premium or bonus squares</span></div><div className="word-direction"><span>ACROSS →</span><span>DOWN ↓</span></div></div><div className="rule-cards">{scene.bullets.map((bullet,index)=><Panel className="rule-card" key={index}><div className="rule-number">{String(index+1).padStart(2,'0')}</div><p>{bullet}</p></Panel>)}</div></div>; }

function ActionsScene({scene,p}: {scene:Scene;p:number}) { const passOnly=/pass/i.test(scene.id)&&!/no.?words/i.test(scene.id); return <div className="actions-scene"><div className="action-comparison"><Panel className="action-card no-words"><div className="action-icon">↻</div><Label>SKIP THIS TURN</Label><h2>No words</h2><p>You stay in the game.<br/>Your future turns continue.</p><div className="action-conditions"><span>✓ Drew at least 1 consonant this turn</span><span>✓ Opponent has not passed</span></div></Panel><Panel className="action-card permanent"><div className="action-icon">✓</div><Label>END ALL YOUR TURNS</Label><h2>Pass forever</h2><p>Your score and clock freeze.<br/>Your opponent can continue alone.</p><div className="action-conditions"><span>Permanent — you cannot return to play</span><span>Both players pass → compare scores</span></div></Panel></div><div className="action-bottom"><strong>Both actions score 0 points.</strong><span>No words is unavailable after a zero-consonant draw or an opponent’s pass.</span></div></div>; }

function ClocksScene({scene,p}: {scene:Scene;p:number}) { const current=300-Math.floor(clamp(p,0,.42)*24);const after=p>.5;const seconds=after?current+30:current;const clock=`${Math.floor(seconds/60)}:${String(seconds%60).padStart(2,'0')}`;return <div className="clocks-scene"><div className="time-options">{[5,15,25].map(value=><span key={value}><strong>{value}</strong>minutes</span>)}<b>+ 30 seconds after each completed turn</b></div><div className="clock-demo"><div className="clock-player active"><Label>YOUR TURN</Label><strong>{clock}</strong><span>{after?'Turn completed · increment added':'Only your clock is running'}</span>{after&&<i>+ 0:30</i>}</div><div className="clock-divider">⇄</div><div className="clock-player"><Label>OPPONENT</Label><strong>5:00</strong><span>Waiting for their next turn</span></div></div><div className="clock-notes"><BulletList items={scene.bullets.slice(0,3)}/></div></div>; }

function RecapScene({scene}: {scene:Scene}) { return <div className="recap-scene"><div className="recap-heading"><Label>YOUR NEXT MOVE</Label><h2>Build a word.<br/>Find a bridge.<br/><em>Make it your best.</em></h2><div className="recap-tiles">{'PLAY'.split('').map((letter,i)=><Tile letter={letter} size={96} key={i}/>)}</div></div><div className="recap-list"><BulletList items={scene.bullets} large/></div></div>; }

function App(){const [frame,setFrame]=useState<FrameInput>({scene:defaultScene,t:0,duration:12,progress:0});updateFrame=setFrame;const {scene,example,t,duration,asset}=frame;const p=clamp(duration>0?t/duration:0);let body:React.ReactNode;switch(scene.kind){case'title':body=t>=3&&asset?<AppScene scene={scene} asset={asset} p={p}/>:<Title scene={scene} p={clamp(t/3)}/>;break;case'letters':body=scene.id==='vowels'?<VowelsScene/>:<LettersScene scene={scene}/>;break;case'draw':body=<DrawScene scene={scene} p={p}/>;break;case'input':body=<InputScene p={p} scene={scene} t={t}/>;break;case'score':body=<ScoreScene example={example} p={p} scene={scene} t={t}/>;break;case'app':body=<AppScene scene={scene} asset={asset} p={p}/>;break;case'actions':body=scene.id==='ending'?<EndingScene/>:<ActionsScene scene={scene} p={p}/>;break;case'clocks':body=['disconnect','recovery'].includes(scene.id)?<RecoveryScene scene={scene} p={p}/>:asset?<AppScene scene={scene} asset={asset} p={p}/>:<ClocksScene scene={scene} p={p}/>;break;case'recap':body=scene.id==='score-recap'?<FormulasScene/>:<RecapScene scene={scene}/>;break;default:body=scene.id==='legal-placement'?<LegalityScene/>:scene.id==='secondary-words'?<LegalityScene secondary/>:scene.id==='setup-ready'?<ReadyScene p={p}/>:scene.id==='word-history'?<HistoryRuleScene/>:scene.id==='rejected-entry'?<RejectedScene p={p}/>:scene.id==='score-intro'?<ScoreIntroScene/>:<RulesScene scene={scene} p={p}/>;}
return <main className="stage" data-scene={scene.id}><Header scene={scene}/><section className={`content kind-${scene.kind}`}>{body}</section><Footer scene={scene} progress={frame.progress??p}/></main>;}

const root=createRoot(document.getElementById('root')!);flushSync(()=>root.render(<App/>));
const settle=()=>new Promise<void>(resolve=>requestAnimationFrame(()=>requestAnimationFrame(()=>resolve())));
function waitEvent(target:HTMLElement,event:string,failed:string,timeout=15000){return new Promise<void>((resolve,reject)=>{let timer:number;const cleanup=()=>{target.removeEventListener(event,success);target.removeEventListener(failed,error);clearTimeout(timer);};const success=()=>{cleanup();resolve();};const error=()=>{cleanup();reject(new Error(`Tutorial asset failed: ${event}`));};target.addEventListener(event,success,{once:true});target.addEventListener(failed,error,{once:true});timer=window.setTimeout(()=>{cleanup();reject(new Error(`Timed out waiting for ${event}`));},timeout);});}
window.renderFrame=async(input)=>{if(!input.scene||!Number.isFinite(input.t)||!Number.isFinite(input.duration))throw new Error('renderFrame requires scene, finite t and finite duration.');flushSync(()=>updateFrame(input));await document.fonts.ready;const video=document.querySelector('video');let mediaTime:number|null=null;if(video){video.pause();if(video.readyState<1)await waitEvent(video,'loadedmetadata','error');const end=Math.max(0,(Number.isFinite(video.duration)?video.duration:input.asset?.duration??input.duration)-.05);const requestedTime=input.scene.id==='welcome'?input.t-3+Math.max(0,end-(input.duration-3)):input.t;mediaTime=clamp(requestedTime,0,end);if(Math.abs(video.currentTime-mediaTime)>.00001||video.readyState<2){const sought=waitEvent(video,'seeked','error');video.currentTime=mediaTime;await sought;}if(video.readyState<2)await waitEvent(video,'loadeddata','error');}const images=Array.from(document.images);await Promise.all(images.map(image=>image.decode()));await settle();return{scene:input.scene.id,t:input.t,mediaTime};};window.tutorialReady=true;
